
function [hFig, hLines, hTitle] = initLivePlot(displayChans, nSamplesPlot, fs)
% INITLIVEPLOT  Build the dark-themed scrolling real-time EEG figure.
%
%   FIX 1: hTitle is now captured from the axes handle obtained INSIDE the
%           loop for subplot 1, not from a second subplot() call outside
%           the loop that was returning a different (stale) axes object.
%   FIX 2: XLim upper bound guarded against 0 when nSamplesPlot==1.
%   FIX 3: Figure 'Position' set via normalized OuterPosition for
%           cross-platform fullscreen behaviour.

    nDisp = numel(displayChans);
    tAxis = (0 : nSamplesPlot-1) / fs;
    tMax  = max(tAxis(end), 1/fs);          % guard against degenerate [0 0]
    blank = zeros(1, nSamplesPlot);

    hFig = figure('Name',        'Live EEG', ...
                  'NumberTitle', 'off', ...
                  'Color',       [0.08 0.08 0.10], ...
                  'Units',       'normalized', ...
                  'OuterPosition',[0 0 1 1]);

    hLines = gobjects(1, nDisp);
    hTitle = [];                            % will be set inside loop

    for k = 1 : nDisp
        ax = subplot(nDisp, 1, k);

        hLines(k) = plot(ax, tAxis, blank, ...
                         'Color',     [0.20 0.85 0.55], ...
                         'LineWidth', 0.8);

        ylabel(ax, sprintf('Ch %d', displayChans(k)), ...
               'Color',    [0.65 0.65 0.65], ...
               'FontSize', 7, ...
               'Rotation', 0, ...           % horizontal labels read better
               'HorizontalAlignment', 'right');

        set(ax, ...
            'XLim',      [0, tMax], ...
            'YLim',      [-200 200], ...    % reasonable EEG start range; auto-adapts
            'Color',     [0.08 0.08 0.10], ...
            'XColor',    [0.35 0.35 0.35], ...
            'YColor',    [0.35 0.35 0.35], ...
            'GridColor', [0.20 0.20 0.20], ...
            'YGrid',     'on', ...
            'XGrid',     'on', ...
            'FontSize',  7, ...
            'TickDir',   'out');

        if k < nDisp
            set(ax, 'XTickLabel', []);
        else
            xlabel(ax, 'Time (s)', 'Color', [0.7 0.7 0.7]);
        end

        % Capture title handle from the FIRST subplot, inside the loop
        if k == 1
            hTitle = title(ax, 'Waiting for data ...', ...
                           'Color',    [0.9 0.9 0.9], ...
                           'FontSize', 10);
        end
    end
end

